# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GameBox
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  pod 'MaterialActivityIndicator'
  pod 'ImageSlideshow'
  pod "ImageSlideshow/Alamofire"

  target 'GameBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GameBoxUITests' do
    # Pods for testing
  end

end
